# Generated by Django 4.2.7 on 2024-01-26 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='email',
            new_name='user_email',
        ),
    ]
