# Generated by Django 4.2.7 on 2024-02-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailing_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['-data_create', '-data_change'], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AddField(
            model_name='mailing',
            name='data_change',
            field=models.DateField(auto_now=True, null=True, verbose_name='дата изменения'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='data_create',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='дата создания'),
        ),
    ]
