# Generated by Django 4.2.7 on 2024-02-04 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_mailing_options_mailing_data_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='data_start',
            field=models.DateField(blank=True, null=True, verbose_name='дата старта рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mailing.statusmailing', verbose_name='статус'),
        ),
    ]
