# Generated by Django 4.2.7 on 2024-02-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-data_create', '-data_change'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AddField(
            model_name='client',
            name='data_change',
            field=models.DateField(auto_now=True, null=True, verbose_name='дата изменения'),
        ),
        migrations.AddField(
            model_name='client',
            name='data_create',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='дата создания'),
        ),
    ]
