# Generated by Django 4.2.7 on 2024-01-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Превью')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержимое')),
                ('data_create', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты в блоге',
            },
        ),
    ]
